name: CI
env:
  HEROKU_CLIENT_APP_NAME: "czegoniejepiotrek"
  HEROKU_SERVER_APP_NAME: "mighty-wildwood-35554"

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        yarn install
      working-directory: "client"
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/$HEROKU_CLIENT_APP_NAME.git
    - name: Deploy to Heroku
      run: |
        git subtree push --prefix client heroku master -f
      
